/home/kevin/音乐/music/xsdz.mp3
/home/kevin/音乐/music/爱江山更爱美人.mp3
/home/kevin/音乐/music/花田错.mp3
/home/kevin/音乐/music/寂寞沙洲冷.mp3
/home/kevin/音乐/music/江山美人.mp3
/home/kevin/音乐/music/两两相忘.mp3
/home/kevin/音乐/music/你怎么说.mp3
/home/kevin/音乐/music/暖风.mp3
/home/kevin/音乐/music/神的传说.mp3
/home/kevin/音乐/music/十面埋伏.mp3
/home/kevin/音乐/music/忐忑.mp3
/home/kevin/音乐/music/听海.mp3
/home/kevin/音乐/music/有多少爱可以重来.mp3
/home/kevin/音乐/music/弱水三千.mp3
/home/kevin/音乐/music/friendship.mp3
/home/kevin/音乐/music/红旗飘飘.mp3
/home/kevin/音乐/music/独上西楼.mp3
/home/kevin/音乐/music/八仙过海.mp3
/home/kevin/音乐/music/改变自己.mp3
/home/kevin/音乐/music/香水毒药.mp3
/home/kevin/音乐/music/追梦人.mp3
/home/kevin/音乐/music/海阔天空.mp3
/home/kevin/音乐/music/光辉岁月.mp3
/home/kevin/音乐/music/问谁领风骚.mp3
/home/kevin/音乐/music/你是我生命中的一首歌.mp3
/home/kevin/音乐/music/783_Baby.mp3
/home/kevin/音乐/music/小小艺术家.mp3
/home/kevin/音乐/music/命运交响曲.mp3
/home/kevin/音乐/music/窗-蔡琴.mp3
/home/kevin/音乐/music/陌生的城市.mp3
/home/kevin/音乐/music/你的背包.mp3
/home/kevin/音乐/music/站起来.mp3
/home/kevin/音乐/music/冲动的惩罚.mp3
/home/kevin/音乐/music/我只在乎你.mp3
/home/kevin/音乐/music/何日君再来.mp3
/home/kevin/音乐/music/北国之春.mp3
/home/kevin/音乐/music/漫步人生.mp3
/home/kevin/音乐/music/最初的梦想.mp3
/home/kevin/音乐/music/一个像秋天一个像春天.mp3
/home/kevin/音乐/music/我终于失去了你.mp3
/home/kevin/音乐/music/又见炊烟.mp3
/home/kevin/音乐/music/亲密爱人.mp3
/home/kevin/音乐/music/滚滚红尘.mp3
/home/kevin/音乐/music/粉红的回忆.mp3
/home/kevin/音乐/music/采红菱.mp3
/home/kevin/音乐/music/渡情.mp3
/home/kevin/音乐/music/大喜宙.mp3
/home/kevin/音乐/music/穷开心.mp3
/home/kevin/音乐/music/蝴蝶泉.mp3
/home/kevin/音乐/music/勇敢勇敢.mp3
/home/kevin/音乐/music/和往事干杯.mp3
/home/kevin/音乐/music/乌苏里船歌.mp3
/home/kevin/音乐/music/风吹麦浪.mp3
/home/kevin/音乐/music/人在旅途.mp3
/home/kevin/音乐/music/鬼迷心窍.mp3
/home/kevin/音乐/music/山丘.mp3
/home/kevin/音乐/music/江南.mp3
/home/kevin/音乐/music/至少还有你.mp3
/home/kevin/音乐/music/原来你在这里.mp3
/home/kevin/音乐/music/晚秋.mp3
/home/kevin/音乐/music/平凡的路.mp3
/home/kevin/音乐/music/风云决.mp3
/home/kevin/音乐/music/一生有你.mp3
/home/kevin/音乐/music/风往北吹.mp3
/home/kevin/音乐/music/用爱将心偷.mp3
/home/kevin/音乐/music/大城小爱.mp3
/home/kevin/音乐/music/时间都哪儿去了 - 主题曲.mp3
/home/kevin/音乐/music/沧海一声笑.mp3
/home/kevin/音乐/music/lemon tree柠檬树.mp3
/home/kevin/音乐/music/深呼吸.mp3
/home/kevin/音乐/music/一剪梅.mp3
/home/kevin/音乐/music/人间道.mp3
/home/kevin/音乐/music/吻别.mp3
/home/kevin/音乐/music/画心.mp3
/home/kevin/音乐/music/发现.mp3
/home/kevin/音乐/music/牧羊曲.mp3
/home/kevin/音乐/music/黄昏.mp3
/home/kevin/音乐/music/关不上的窗.mp3
/home/kevin/音乐/music/最近比较烦.mp3
