/home/kevin/音乐/music/追梦人.mp3
/home/kevin/音乐/music/xsdz.mp3
/home/kevin/音乐/music/爱江山更爱美人.mp3
/home/kevin/音乐/music/八仙过海.mp3
/home/kevin/音乐/music/花田错.mp3
/home/kevin/音乐/music/寂寞沙洲冷.mp3
/home/kevin/音乐/music/江山美人.mp3
/home/kevin/音乐/music/两两相忘.mp3
/home/kevin/音乐/music/你怎么说.mp3
/home/kevin/音乐/music/暖风.mp3
/home/kevin/音乐/music/神的传说.mp3
/home/kevin/音乐/music/十面埋伏.mp3
/home/kevin/音乐/music/忐忑.mp3
/home/kevin/音乐/music/听海.mp3
/home/kevin/音乐/music/有多少爱可以重来.mp3
/home/kevin/音乐/music/独上西楼.mp3
/home/kevin/音乐/music/弱水三千.mp3
/home/kevin/音乐/music/改变自己.mp3
/home/kevin/音乐/music/friendship.mp3
/home/kevin/音乐/music/香水毒药.mp3
/home/kevin/音乐/music/红旗飘飘.mp3
/home/kevin/音乐/music/追梦人.mp3
