# vivado setting
export PATH=$PATH:/home/kevin/xilinx/Vivado/2019.2/bin

# basic-script setting
export PATH=$PATH:/home/kevin/bash-script

export LD_LIBRARY_PATH=/home/kevin/clang/lib:/home/kevin/library_tools_game_repository/llvm/lib/:/usr/local/lib:/lib:/usr/lib:/opt/spb16/tools.lnx86/lib:/opt/spb16/tools.lnx86/mainwin520/mw/lib-linux_optimized/:/home/kevin/armworkcopy/Venture_Game/lib_x86/lib

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

export GITHUB_USER=veerwang
export GITHUB_PASSWORD=v200431060
