# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"

#ZSH_THEME="fletcherm"
#ZSH_THEME="strug"
#ZSH_THEME="ys"
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

export DISABLE_AUTO_TITLE="true"

setopt AUTO_LIST
setopt AUTO_MENU
setopt MENU_COMPLETE

autoload -U compinit
compinit

# Completion caching
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path .zcache
#zstyle ':completion:*:cd:*' ignore-parents parent pwd

#Completion Options
zstyle ':completion:*:match:*' original only
zstyle ':completion::prefix-1:*' completer _complete
zstyle ':completion:predict:*' completer _complete
zstyle ':completion:incremental:*' completer _complete _correct
zstyle ':completion:*' completer _complete _prefix _correct _prefix _match _approximate

# Path Expansion
zstyle ':completion:*' expand 'yes'
zstyle ':completion:*' squeeze-shlashes 'yes'
zstyle ':completion::complete:*' '\\'

zstyle ':completion:*:*:*:default' menu yes select
zstyle ':completion:*:*:default' force-list always

# GNU Colors 需要/etc/DIR_COLORS文件 否则自动补全时候选菜单中的选项不能彩色显示
[ -f /etc/DIR_COLORS ] && eval $(dircolors -b /etc/DIR_COLORS)
export ZLSCOLORS="${LS_COLORS}"
zmodload zsh/complist
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

compdef pkill=kill
compdef pkill=killall
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:processes' command 'ps -au$USER'

# Group matches and Describe
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format $'\e[01;33m -- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[01;35m -- %d --\e[0m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found --\e[0m'

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ruby rvm autojump tmux tmuxinator sudo fasd github cp extract tig history-substring-search themes archlinux)

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

source $ZSH/oh-my-zsh.sh

export JAVA_HOME=/usr/lib/jvm/default/
export JRE_HOME=/usr/lib/jvm/default-runtime/jre

export M2_HOME=/opt/maven

export CLASSPATH=/usr/share/java/:/usr/local/lib/antlrworks-1.5.jar:/usr/local/lib/antlr-3.5.2-complete-no-st3.jar:/usr/share/java/antlr.jar:$CLASSPATH

export PATH=$PATH:/home/kevin/clang/bin:$HOME/bin:/opt/host/gcc-4.9.3/bin/:/usr/bin/:/usr/local/lib:/usr/local/bin:/usr/local/sbin:/sbin/:/usr/sbin:/opt/skyeye/bin/:/opt/host/arm-wangwei-linux-gnueabi/bin:/opt/host/arm-kevin-linux-gnueabi/bin:/home/kevin/freetype/include/freetype2/:/opt/host/arm-1176-linux-gnueabi/bin:/opt/host/gcc-arm-none-eabi-4_7-2013q3/bin/:/opt/host/gcc-linaro/bin/:$M2_HOME/bin:$JAVA_HOME/bin:$JRE_HOME/bin

#export TERM=xterm-256color

alias ge='cd ~/library_tools_game_repository/elementary_library/src_git/library-src-repository/'
alias tool='~/library_tools_game_repository'

alias um='umount /media/KINGSTON/'

alias odn='sudo ifup /etc/sysconfig/network-scripts/ifcfg-ARM_调试网络'
alias cdn='sudo ifdown /etc/sysconfig/network-scripts/ifcfg-ARM_调试网络'

alias onn='sudo ifup /etc/sysconfig/network-scripts/ifcfg-eth0'
alias cnn='sudo ifdown /etc/sysconfig/network-scripts/ifcfg-eth0'

alias config='vim ~/.zshrc' 

hash -d  armgcc='/opt/host/arm-kevin-linux-gnueabi/bin/'

alias ccheck='~/bin/cppcheck --enable=all --library=std,posix'

# trash-cli tools command used
alias trm=trash-put
alias tl=trash-list
alias ts=trash-restore
alias tclean=trash-empty
alias rm!="/bin/rm -vi"
alias rm=trash

alias td=todo.sh

#alias sprox="sslocal -s hk02-3.ssv7.net -p 14276 -l 1080 -k qfLgtMsMVAy5 -m aes-256-cfb"
alias sprox="sslocal -s hk1-sta3.06e59.space -p 14276 -l 1080 -k qfLgtMsMVAy5 -m chacha20-ietf-poly1305"
#alias sprox="sslocal -s hk1-sta3.06e59.space -p 14276 -l 1080 -k qfLgtMsMVAy5 -m chacha20"
#alias sprox="sslocal -s jp01-3.ssv7.net -p 14276 -l 1080 -k qfLgtMsMVAy5 -m aes-256-cfb"

alias account="ledger -f ~/DataLibrary/kevin.wang-account/ledger/kevin-ledger.ldg"
alias money="vim ~/DataLibrary/kevin.wang-account/ledger/kevin-ledger.ldg"

# jack workingspace begin
alias ovm="virtualbox --startvm"
alias drom="smbclient //192.168.31.146/home -U smb"	# password: smb
# jack workingspace end

#alsi --red

#alias dw="tmux -2 new -s basic"
alias dw="tmuxomatic ~/.tmux/workspace"
#alias dp="tmuxomatic ~/.tmux/play"
alias dp="tmuxp load ~/work.yaml"
alias web="proxychains4 w3m"
#source ~/library_tools_game_repository/incr-0.2.zsh

alias mgrep='grep -n -r --exclude-dir=".git" --exclude-dir=".svn" --binary-files=without-match --exclude="*.py"'

source ~/library_tools_game_repository/z/z.sh

source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

[[ -s /home/kevin/.autojump/etc/profile.d/autojump.sh  ]] && source /home/kevin/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u
