# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"

#ZSH_THEME="fletcherm"
ZSH_THEME="strug"
#ZSH_THEME="tonotdo"
#ZSH_THEME="linuxonly"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ruby rvm tmux tmuxinator sudo fasd github cp extract themes ubuntu tig)

source $ZSH/oh-my-zsh.sh

export JAVA_HOME=/usr/lib/jvm/default-java/
export JRE_HOME=/usr/lib/jvm/default-java/jre
export CLASSPATH=$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export CLASSPATH=.:$CLASSPATH

export CLASSPATH=/usr/share/java/:/usr/local/lib/antlrworks-1.5.jar:/usr/local/lib/antlr-3.5.2-complete-no-st3.jar:/usr/share/java/antlr.jar:$CLASSPATH

export PATH=$HOME/bin/gradle-6.0.1/bin:$PATH:/home/kevin/android-studio/android-studio/bin:$HOME/bin:/home/kevin/android-sdk-linux/build-tools/28.0.3/:/usr/bin/:/usr/local/lib:/usr/local/bin:/usr/local/sbin:/sbin/:/usr/sbin:/opt/skyeye/bin/:/opt/host/arm-wangwei-linux-gnueabi/bin:/opt/host/arm-kevin-linux-gnueabi/bin:/home/kevin/freetype/include/freetype2/:/opt/host/arm-1176-linux-gnueabi/bin:/opt/host/gcc-arm-none-eabi-4_7-2013q3/bin/:/opt/host/gcc-linaro/bin/:$M2_HOME/bin:$JAVA_HOME/bin:$JRE_HOME/bin:$HOME/android-sdk-linux/tools:/mnt/android-ndk-r20/build:/home/kevin/auto-test-framework/android-wts/testsuite:/home/kevin/auto-test-framework/android-wts/tools

export LD_LIBRARY_PATH=nn/home/kevin/library_tools_game_repository/llvm/lib/:/usr/local/lib:/lib:/usr/lib:/opt/spb16/tools.lnx86/lib:/opt/spb16/tools.lnx86/mainwin520/mw/lib-linux_optimized/:/home/kevin/armworkcopy/Venture_Game/lib_x86/lib

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

# export TERM=xterm-256color

# Customize to your needs...

alias config='vim ~/.zshrc' 

# trash-cli tools command used
alias trm=trash-put
alias tl=trash-list
alias ts=trash-restore
alias tclean=trash-empty
alias rm!="/bin/rm -vi"
alias rm=trash

alias sprox="sslocal -s hk02-18.ssv7.net -p 26392 -l 1080 -k M5bjRlGMQO66 -m aes-256-cfb"

alias mgrep='grep -n -r --exclude-dir=".git" --exclude-dir=".svn" --binary-files=without-match --exclude="*.py"'

alias loin='ssh root@192.168.1.110'
alias l70='ssh wwei@172.27.16.70'
alias l80='ssh wwei@172.27.16.80'

source ~/z/z.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GOPATH="$HOME/goworkspace"
